#!/bin/bash

echo "🎯 WhisperMate iOS Target Setup Helper"
echo "======================================"
echo ""

# Check if Xcode is open
if pgrep -x "Xcode" > /dev/null; then
    echo "✅ Xcode is running"
else
    echo "⚠️  Xcode is not running - opening now..."
    open Whispermate.xcodeproj
    sleep 3
fi

echo ""
echo "📋 Manual Steps Required in Xcode:"
echo ""
echo "STEP 1: Create WhisperMateShared Framework"
echo "  1. In Xcode, click File > New > Target"
echo "  2. Select 'Framework' under iOS"
echo "  3. Product Name: WhisperMateShared"
echo "  4. Click Finish"
echo ""
read -p "Press ENTER when Step 1 is complete..."

echo ""
echo "STEP 2: Add Files to WhisperMateShared"
echo "  1. In Project Navigator, select files in WhisperMateShared/ folder"
echo "  2. In File Inspector (right panel), check 'WhisperMateShared' under Target Membership"
echo "  3. Add ALL files from:"
echo "     - WhisperMateShared/Models/"
echo "     - WhisperMateShared/Networking/"
echo "     - WhisperMateShared/Services/"
echo "     - WhisperMateShared/Storage/"
echo ""
read -p "Press ENTER when Step 2 is complete..."

echo ""
echo "STEP 3: Create WhisperMateIOS App"
echo "  1. Click File > New > Target"
echo "  2. Select 'App' under iOS"
echo "  3. Product Name: WhisperMateIOS"
echo "  4. Bundle ID: com.whispermate.ios"
echo "  5. Interface: SwiftUI"
echo "  6. Click Finish"
echo "  7. DELETE default ContentView.swift and WhisperMateIOSApp.swift"
echo ""
read -p "Press ENTER when Step 3 is complete..."

echo ""
echo "STEP 4: Add Files to WhisperMateIOS"
echo "  1. Add WhisperMateIOS/ files to target:"
echo "     - WhisperMateApp.swift"
echo "     - OnboardingView.swift"
echo "     - MainView.swift"
echo "  2. Set Info.plist to WhisperMateIOS/Info.plist"
echo ""
read -p "Press ENTER when Step 4 is complete..."

echo ""
echo "STEP 5: Link Framework to iOS App"
echo "  1. Select WhisperMateIOS target"
echo "  2. General tab > Frameworks, Libraries, and Embedded Content"
echo "  3. Click + button"
echo "  4. Add WhisperMateShared.framework"
echo ""
read -p "Press ENTER when Step 5 is complete..."

echo ""
echo "STEP 6: Configure App Groups for iOS App"
echo "  1. Select WhisperMateIOS target"
echo "  2. Signing & Capabilities tab"
echo "  3. Click + Capability"
echo "  4. Add 'App Groups'"
echo "  5. Click + and add: group.com.whispermate.shared"
echo ""
read -p "Press ENTER when Step 6 is complete..."

echo ""
echo "STEP 7: Create WhisperMateKeyboard Extension"
echo "  1. Click File > New > Target"
echo "  2. Select 'Custom Keyboard Extension' under iOS"
echo "  3. Product Name: WhisperMateKeyboard"
echo "  4. Bundle ID: com.whispermate.ios.keyboard"
echo "  5. Click Finish"
echo "  6. Click 'Activate' when prompted"
echo "  7. DELETE default KeyboardViewController.swift"
echo ""
read -p "Press ENTER when Step 7 is complete..."

echo ""
echo "STEP 8: Add Files to Keyboard Extension"
echo "  1. Add WhisperMateKeyboard/KeyboardViewController.swift"
echo "  2. Set Info.plist to WhisperMateKeyboard/Info.plist"
echo ""
read -p "Press ENTER when Step 8 is complete..."

echo ""
echo "STEP 9: Link Framework to Keyboard Extension"
echo "  1. Select WhisperMateKeyboard target"
echo "  2. General tab > Frameworks, Libraries, and Embedded Content"
echo "  3. Click + button"
echo "  4. Add WhisperMateShared.framework"
echo ""
read -p "Press ENTER when Step 9 is complete..."

echo ""
echo "STEP 10: Configure App Groups for Keyboard"
echo "  1. Select WhisperMateKeyboard target"
echo "  2. Signing & Capabilities tab"
echo "  3. Click + Capability"
echo "  4. Add 'App Groups'"
echo "  5. Click + and add: group.com.whispermate.shared"
echo ""
read -p "Press ENTER when Step 10 is complete..."

echo ""
echo "🔨 Building targets..."
xcodebuild -scheme WhisperMateIOS -sdk iphonesimulator -configuration Debug build

if [ $? -eq 0 ]; then
    echo ""
    echo "✅ BUILD SUCCESSFUL!"
    echo ""
    echo "🚀 Next Steps:"
    echo "  1. Connect an iOS device (keyboard extensions don't work in simulator)"
    echo "  2. In Xcode, select WhisperMateIOS scheme"
    echo "  3. Select your device as destination"
    echo "  4. Click Run (⌘R)"
    echo ""
    echo "📱 After running on device:"
    echo "  1. Complete onboarding in the app"
    echo "  2. Go to Settings > General > Keyboard > Keyboards"
    echo "  3. Add WhisperMate keyboard"
    echo "  4. Enable 'Allow Full Access'"
    echo "  5. Test in any app with text input"
else
    echo ""
    echo "❌ BUILD FAILED - Please check Xcode for errors"
fi
